# Generated by Django 3.1.6 on 2021-02-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectosyempresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapaproyecto',
            options={'verbose_name': 'Etapas de proyectos'},
        ),
    ]
