# Generated by Django 3.1.6 on 2021-02-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectosyempresas', '0003_auto_20210221_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelestudio',
            options={'verbose_name': 'Niveles de estudio'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Paise'},
        ),
    ]
