# Generated by Django 3.1.6 on 2021-02-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectosyempresas', '0004_auto_20210221_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelestudio',
            options={},
        ),
        migrations.AlterModelTable(
            name='nivelestudio',
            table='Nivel de estudios',
        ),
    ]
