# Generated by Django 3.1.6 on 2021-02-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectosyempresas', '0005_auto_20210221_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadeconomica',
            options={'verbose_name_plural': 'Actividades economicas'},
        ),
        migrations.AlterModelOptions(
            name='divisionterritorial',
            options={'verbose_name_plural': 'Divisiones territoriales'},
        ),
        migrations.AlterModelOptions(
            name='etapaproyecto',
            options={'verbose_name_plural': 'Etapas de proyectos'},
        ),
        migrations.AlterModelOptions(
            name='informacioncontactoempresa',
            options={'verbose_name_plural': 'Contactos de empresas'},
        ),
        migrations.AlterModelOptions(
            name='modelonegocio',
            options={'verbose_name_plural': 'Modelos de negocio'},
        ),
        migrations.AlterModelOptions(
            name='nivelestudio',
            options={'verbose_name_plural': 'Niveles de estudio'},
        ),
        migrations.AlterModelOptions(
            name='ocupacion',
            options={'verbose_name_plural': 'Ocupaciones'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='profesion',
            options={'verbose_name_plural': 'Profesiones'},
        ),
        migrations.AlterModelOptions(
            name='proyectoempresarial',
            options={'verbose_name_plural': 'Proyectos empresariales'},
        ),
        migrations.AlterModelOptions(
            name='tamanoempresa',
            options={'verbose_name_plural': 'Tamaños de empresas'},
        ),
        migrations.AlterModelOptions(
            name='tiposociedad',
            options={'verbose_name_plural': 'Tipos de sociedades'},
        ),
        migrations.AlterModelTable(
            name='nivelestudio',
            table=None,
        ),
    ]
