# Generated by Django 3.1.6 on 2021-02-23 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectosyempresas', '0009_auto_20210222_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoempresarial',
            name='persona_contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectosyempresas.proyectoempresarial', verbose_name='Persona contacto:'),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
