# Generated by Django 3.1.6 on 2021-02-23 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proyectosyempresas', '0010_auto_20210223_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre de la persona*:')),
                ('id_persona', models.CharField(max_length=80, verbose_name='Identificación de la persona*:')),
            ],
        ),
        migrations.AlterField(
            model_name='proyectoempresarial',
            name='persona_contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectosyempresas.persona', verbose_name='Persona contacto:'),
        ),
    ]
